# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 12:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('race', models.CharField(choices=[('breton', 'BRETON'), ('orc', 'ORC'), ('redguard', 'REDGUARD'), ('high elf', 'HIGH ELF'), ('wood elf', 'WOOD ELD'), ('khajiit', 'KHAJIIT'), ('argonian', 'ARGONIAN'), ('dark elf', 'DARK ELF'), ('nord', 'NORD')], default='breton', max_length=6)),
                ('classes', models.CharField(choices=[('dragonknight', 'DRAGONKNIGHT'), ('sorcerer', 'SORCERER'), ('nightblade', 'NIGHTBLADE'), ('templar', 'TEMPLAR'), ('warden', 'WARDEN')], default='dragonknight', max_length=6)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('views', models.IntegerField(default=0)),
                ('tag', models.CharField(blank=True, max_length=30, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
