# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-04 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='character',
            name='views',
        ),
        migrations.AddField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=6),
        ),
    ]
