# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-04 08:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_auto_20180404_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='gender',
        ),
    ]
