# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-04 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_remove_character_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('male', 'M'), ('female', 'F')], default='male', max_length=6),
        ),
    ]
