# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-04 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_character_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('m', 'MALE'), ('f', 'FEMALE')], default='m', max_length=6),
        ),
    ]
