# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0005_auto_20180404_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='classes',
            field=models.CharField(choices=[('dragonknight', 'DRAGONKNIGHT'), ('sorcerer', 'SORCERER'), ('nightblade', 'NIGHTBLADE'), ('templar', 'TEMPLAR'), ('warden', 'WARDEN')], default='dragonknight', max_length=20),
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('m', 'MALE'), ('f', 'FEMALE')], default='m', max_length=20),
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.CharField(choices=[('breton', 'BRETON'), ('orc', 'ORC'), ('redguard', 'REDGUARD'), ('high elf', 'HIGH ELF'), ('wood elf', 'WOOD ELD'), ('khajiit', 'KHAJIIT'), ('argonian', 'ARGONIAN'), ('dark elf', 'DARK ELF'), ('nord', 'NORD')], default='breton', max_length=20),
        ),
    ]
