# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 09:04
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0008_character_guild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='guild',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('fighters', 'FIGHTERS'), ('mages', 'MAGES'), ('undaunted', 'UNDAUNTED'), ('thieves', 'THIEVES'), ('dark brotherhood', 'DARK BROTHERHOOD')], max_length=20),
        ),
    ]
