# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-29 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180329_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlc',
            name='category',
            field=models.CharField(default=' ', max_length=254),
        ),
    ]
